# Generated by Django 5.0.6 on 2025-10-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat', '0002_alter_message_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
