"""
Django settings for ice project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

from pathlib import Path

import os
from dotenv import load_dotenv
from pathlib import Path

# Load .env file
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#t$vg2*4ui77g^m!=noz06auz3vuix!-blqdb^-zczqu7nx0g6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "cozy-enchantment-production.up.railway.app",
    "www.linklovers.ng",
    "linklovers.ng",
    "ice-inro.onrender.com",
    "127.0.0.1",  # Keep this for local development
    "localhost",   # Also useful for debugging
]

CSRF_TRUSTED_ORIGINS = [
    "https://cozy-enchantment-production.up.railway.app",
    "https://ice-inro.onrender.com",
    "https://www.linklovers.ng",
    "https://linklovers.ng"
]


# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'blog',
    'community',
    'pages',
    'chat',
    'channels',
    'members',
    'tasks',
    'django_celery_beat',
    'cloudinary',
    'cloudinary_storage',
    'realtime_chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.active_user_middleware.ActiveUserMiddleware',
    'chat.middleware.NoCacheMiddleware',
]

ROOT_URLCONF = 'ice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.new_message_flag',
            ],
        },
    },
]

WSGI_APPLICATION = 'ice.wsgi.application'

# Channels settings
ASGI_APPLICATION = 'ice.asgi.application'

# Redis settings for Channels (ensure Redis is installed and running)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                "redis://default:7817FguydxnXkAr2pcv1ZlY9ogWZ0J8y@redis-12290.c85.us-east-1-2.ec2.redns.redis-cloud.com:12290"
            ],
            # 'hosts': [('127.0.0.1', 6379)],  # Redis must be installed and running
        },
    },
}



# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# import dj_database_url
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }




import os

# Directly add your database URL here
# DATABASE_URL = "postgresql://link_db_p4un_user:AjPBlWXQwkb9IiEMyf7IPS7wUP9n6ooB@dpg-d1ugrf3e5dus73dnj2jg-a.oregon-postgres.render.com:5432/link_db_p4un"
#
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'link_db_p4un',  # Extract dbname from URL
#         'USER': 'link_db_p4un_user',  # Extract user from URL
#         'PASSWORD': 'AjPBlWXQwkb9IiEMyf7IPS7wUP9n6ooB',  # Extract password from URL
#         'HOST': 'dpg-d1ugrf3e5dus73dnj2jg-a.oregon-postgres.render.com',  # Extract host from URL
#         'PORT': '5432',  # Corrected extraction of port
#     }
# }


# DATABASE_URL = "postgresql://postgres.dspxvkiqrxviiinfvbyl:[YOUR-PASSWORD]@aws-0-eu-west-2.pooler.supabase.com:5432/postgres"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.dspxvkiqrxviiinfvbyl',
        'PASSWORD': 'XpUO6qH9j7PCzy4B',
        'HOST': 'aws-0-eu-west-2.pooler.supabase.com',
        'PORT': '5432',
    }
}



# media hosting
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dstefwn3l',
    'API_KEY': '235168181554165',
    'API_SECRET': 'g1eSXg-ryFRKKBkWRPB7gF4Kd1I',
    'RESOURCE_TYPE': 'auto'
}

import cloudinary

cloudinary.config(
    cloud_name = "dstefwn3l",
    api_key = "235168181554165",
    api_secret = "g1eSXg-ryFRKKBkWRPB7gF4Kd1I",
    resource_type = "auto"
)




# import dj_database_url
# from dotenv import load_dotenv
#
# load_dotenv()
#
# DATABASES = {
#     'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
# }




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Email Configuration (Use an SMTP server)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '92c9d0001@smtp-brevo.com'
EMAIL_HOST_PASSWORD = 'xsmtpsib-ab7b5dd16565e4ffeb8e6c25a04853394cc7fb701698f4b13e2a6bdd79171da8-rA4zsv12K8mfV3Qh'
DEFAULT_FROM_EMAIL = 'Link Lovers<linkloversng@gmail.com>'

# EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
#
# ANYMAIL = {
#      "SENDINBLUE_API_KEY": "xsmtpsib-ab7b5dd16565e4ffeb8e6c25a04853394cc7fb701698f4b13e2a6bdd79171da8-rA4zsv12K8mfV3Qh"
# }
#
# DEFAULT_FROM_EMAIL = "Link Lovers <no-reply@yourdomain.com>"



CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = BASE_DIR/'media'

import os
from django.conf import settings

# Local storage path for video uploads
VIDEO_MEDIA_ROOT = os.path.join(BASE_DIR, 'media/videos')
VIDEO_MEDIA_URL = '/media/videos/'


# Enable WhiteNoise to serve static files
MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

# LOGOUT_REDIRECT_URL = '/'
# LOGIN_REDIRECT_URL = '/accounts/dashboard'

AUTH_USER_MODEL = 'accounts.User'
# AUTH_USER_MODEL = 'auth.User'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
