# Generated by Django 5.0.6 on 2025-06-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
