# Generated by Django 5.0.6 on 2025-07-29 10:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_status_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
