# Generated by Django 5.0.6 on 2025-07-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_status_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='statuses/'),
        ),
    ]
