# Generated by Django 5.0.6 on 2025-07-30 10:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_status_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='media',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='media'),
        ),
    ]
