# Generated by Django 5.0.6 on 2025-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_status_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
