# Generated by Django 5.0.6 on 2025-07-30 10:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_status_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='media',
        ),
        migrations.AddField(
            model_name='status',
            name='image_media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='status',
            name='video_media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
