# Generated by Django 5.0.6 on 2025-08-02 10:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_status_media_status_image_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='image_media',
        ),
        migrations.RemoveField(
            model_name='status',
            name='video_media',
        ),
        migrations.AddField(
            model_name='status',
            name='media',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='media'),
        ),
    ]
