# Generated by Django 5.0.6 on 2025-08-02 10:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_status_image_media_remove_status_video_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='media',
        ),
        migrations.AddField(
            model_name='status',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='status',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
