# Generated by Django 5.0.6 on 2025-05-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_checked_messages_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
