# Generated by Django 5.0.6 on 2025-07-28 10:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
