# Generated by Django 5.0.6 on 2025-07-29 10:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_user_image1_alter_user_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
