# Generated by Django 5.0.6 on 2025-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
