# Generated by Django 5.0.6 on 2025-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='text',
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
