# Generated by Django 5.0.6 on 2025-05-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_status_text_alter_status_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
